[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "For parsing/writing dumb filetypes."
!!LICENSE-PERMISSIVE
!!DEFAULT-EDITION

[lib]
path = "lib.rs"

[dependencies]
!!itertools
!!failure
!!vasp-poscar
!!log
!!serde
!!serde_derive
!!serde_yaml

!!rsp2-structure
!!rsp2-array-types
!!rsp2-array-utils
!!rsp2-soa-ops
!!rsp2-util-macros

[features]
!!NIGHTLY-FEATURE-LINE
